// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myizam.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Myizam.Data.Migrations
{
    [DbContext(typeof(MyizamDbContext))]
    [Migration("20260715094759_AskPipelineSchema")]
    partial class AskPipelineSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Myizam.Data.AnswerCacheEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("AnswerJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Key");

                    b.ToTable("answer_cache", (string)null);
                });

            modelBuilder.Entity("Myizam.Data.ChunkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArticleNumber")
                        .HasColumnType("text")
                        .HasColumnName("article_number");

                    b.Property<string>("ArticleTitle")
                        .HasColumnType("text")
                        .HasColumnName("article_title");

                    b.Property<string>("Chapter")
                        .HasColumnType("text")
                        .HasColumnName("chapter");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("header");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ru")
                        .HasColumnName("lang");

                    b.Property<string>("LawCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("law_code");

                    b.Property<int>("Part")
                        .HasColumnType("integer")
                        .HasColumnName("part");

                    b.Property<int>("PartCount")
                        .HasColumnType("integer")
                        .HasColumnName("part_count");

                    b.Property<string>("Section")
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("LawCode", "ArticleNumber");

                    b.ToTable("chunks", (string)null);
                });

            modelBuilder.Entity("Myizam.Data.EmbeddingCacheEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.HasKey("Key");

                    b.ToTable("embedding_cache", (string)null);
                });

            modelBuilder.Entity("Myizam.Data.LawEntity", b =>
                {
                    b.Property<string>("DocumentCode")
                        .HasColumnType("text")
                        .HasColumnName("document_code");

                    b.Property<int>("ArticleCount")
                        .HasColumnType("integer")
                        .HasColumnName("article_count");

                    b.Property<DateOnly>("EditionDate")
                        .HasColumnType("date")
                        .HasColumnName("edition_date");

                    b.Property<long>("EditionId")
                        .HasColumnType("bigint")
                        .HasColumnName("edition_id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("official_name");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("DocumentCode");

                    b.ToTable("laws", (string)null);
                });

            modelBuilder.Entity("Myizam.Data.QueryLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("AnswerLang")
                        .HasColumnType("text")
                        .HasColumnName("answer_lang");

                    b.Property<bool>("CacheHit")
                        .HasColumnType("boolean")
                        .HasColumnName("cache_hit");

                    b.Property<long[]>("CitedChunkIds")
                        .HasColumnType("bigint[]")
                        .HasColumnName("cited_chunk_ids");

                    b.Property<string>("ClientHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_hash");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(8,5)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<bool?>("GuardGrounded")
                        .HasColumnType("boolean")
                        .HasColumnName("guard_grounded");

                    b.Property<string>("GuardModel")
                        .HasColumnType("text")
                        .HasColumnName("guard_model");

                    b.Property<double?>("GuardScore")
                        .HasColumnType("double precision")
                        .HasColumnName("guard_score");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("QuestionLang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_lang");

                    b.Property<string>("QuestionRu")
                        .HasColumnType("text")
                        .HasColumnName("question_ru");

                    b.Property<bool>("Refused")
                        .HasColumnType("boolean")
                        .HasColumnName("refused");

                    b.Property<int>("TokensIn")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_in");

                    b.Property<int>("TokensOut")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_out");

                    b.Property<double?>("TopSimilarity")
                        .HasColumnType("double precision")
                        .HasColumnName("top_similarity");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ClientHash", "CreatedAt");

                    b.ToTable("query_log", (string)null);
                });

            modelBuilder.Entity("Myizam.Data.ChunkEntity", b =>
                {
                    b.HasOne("Myizam.Data.LawEntity", "Law")
                        .WithMany("Chunks")
                        .HasForeignKey("LawCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Law");
                });

            modelBuilder.Entity("Myizam.Data.LawEntity", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
